In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([2,3,4])

In [12]:
b.dtype

dtype('int32')

In [13]:
c = np.array([1.2, 3.5,5.1])

In [14]:
c.dtype

dtype('float64')

In [15]:
c = np.array([[1,2],[2,4]],dtype=complex)

In [16]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
#Expresiones Lambda 
def f(x,y,z=1):
    return (x+y) *z
f(5,6)

11

In [18]:
fun_l = lambda x, y, z =1 : (x+y)*z

In [20]:
fun_l(5,6)

11

In [24]:
lista_a = [0, 1, -1, -2, 3, -4, 5, 6, 7]

In [30]:
lista_b = filter(lambda x: x > 0, lista_a)

In [31]:
print(list(lista_b)) #Es necesario castear a lo que se necesite , en este caso a una lista 


[1, 3, 5, 6, 7]


In [35]:
li = [1,2,3]
new_li = map(lambda x: x + 2 , li)
for item in new_li: 
    print(item)

3
4
5


In [36]:
type(new_li)

map

In [37]:
from functools import reduce
producto = reduce((lambda x, y: x*y), [1, 2, 3, 4])

In [38]:
print(producto)

24
